# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6801560d29d47e1ca2685f5028ae4cee516265bde51b34d215c33c4df6954da24c0530e0a9d846b975c037c1776054d06760a805a333d3b4182deb2e5cbd537c

test:
  secret_key_base: 9b736a51e9ec455b3ef19e38192f293b471fb17c0b417d9351bd1904a70d19022d3d3fc5fe06128574ec067c41a52a8e5ef14d59b329d719946b76226b2b651c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
